#include "vfs.h"

VFS::VFS() {
    addNode(0, "root", "dir", "4.0 K", "2026-03-21", "", -1);
    addNode(1, "about", "dir", "4.0 K", "2026-03-21", "", 0);
    addNode(2, "projects", "dir", "4.0 K", "2026-03-21", "", 0);
    addNode(3, "experience", "dir", "4.0 K", "2026-03-21", "", 0);
    addNode(4, "education", "dir", "4.0 K", "2026-03-21", "", 0);
    addNode(5, "certification&awards", "dir", "4.0 K", "2026-03-21", "", 0);
    addNode(6, "social", "dir", "4.0 K", "2026-03-21", "", 0);
    addNode(7, "RefPedia", "dir", "4.0 K", "2026-03-21", "", 2);
    addNode(8, "NightDrive", "dir", "4.0 K", "2026-03-21", "", 2);
    addNode(9, "portofolio", "dir", "4.0 K", "2026-03-21", "", 2);
    addNode(10, "jobs", "dir", "4.0 K", "2026-03-21", "", 3);
    addNode(11, "community", "dir", "4.0 K", "2026-03-21", "", 3);
    addNode(12, "Erasmus", "dir", "4.0 K", "2026-03-21", "", 3);
    addNode(101, "bio.txt", "txt", "4.0 K", "2026-03-21", "Hi, I’m Mihai Arisanu, a final-year high school student with a strong interest in computer science. I’m a creative and collaborative person who enjoys working in team environments and contributing to shared goals.\n\nI’m particularly passionate about low-level programming, while also developing practical mobile applications designed to improve everyday life.\n\nOutside of tech, I enjoy playing basketball and following the game whenever I can.", 1);
    addNode(102, "career_stats.txt", "txt", "4.0 K", "2026-03-21", "=========================================\nPLAYER STATS: MIHAI ARISANU\n\nPOSITION : Final-Year of Highschool Student\nPLAY STYLE : Takes on any challenge & thrives in problem-solving\nTECH STACK : C++, JavaScript, Mobile Development\nSIGNATURE MOVE : Building efficient, real-world applications\n\nBONUS TRAIT : Creative team player with a passion for collaboration\nOFF COURT : Basketball enthusiast (player & fan)", 1);
    addNode(103, "les_patachous.txt", "txt", "4.0 K", "2026-03-21", "Volunteering at kindergarten \"Les Patachous\", Bassecourt Switzerland | 2 weeks\n            • Assisted staff with daily activities\n            • Supported child development activities\n\nLink to their website: https://mehs.ch/les-patachous/presentation/", 11);
    addNode(104, "highschool.txt", "txt", "4.0 K", "2026-03-21", "High School Education (2022–2026)\nMircea cel Bătrân National College, Rm. Vâlcea, Romania\n\nKey Skills & Knowledge Acquired:\n\n- C++ Programming:\n    • Algorithmic thinking and problem-solving\n    • Data structures: vectors, matrices\n    • Basics of graphs, dynamic programming, and greedy algorithms\n\n- Machine Learning Foundations:\n    • Data manipulation and analysis in Python\n    • Applied basic ML algorithms:\n        - Linear Regression\n        - Logistic Regression\n        - k-Nearest Neighbors (k-NN)\n        - Random Forest", 4);
    addNode(105, "certifications.txt", "txt", "4.0 K", "2026-03-21", "IELTS band 7 (CEFR: C1)\nFIBA Table Official Certification\nIC3", 5);
    addNode(106, "github.sh", "exec", "4.0 K", "2026-03-21", "https://github.com/MihaiArisanu", 6);
    addNode(107, "linkedin.sh", "exec", "4.0 K", "2026-03-21", "https://www.linkedin.com/in/mihai-arisanu-4999452a5/", 6);
    addNode(108, "RefPedia_presentation.txt", "txt", "4.0 K", "2026-03-21", "RefPedia — App Overview\n\nRefPedia is a mobile app for aspiring and active basketball referees to learn, practice, and test their officiating skills. Available on iOS and Android, it combines video lessons, interactive quizzes, camera-based exercises, and exam simulations — all in one app.\n\n\"Turn your passion for basketball into professional skills!\" 🏀\n\nThe Challenge\n\nTraditional referee training relies on rulebooks and in-person clinics: slow, inflexible, and non-interactive. There was no mobile tool to study, practice, and test referees on the go.\n\nOur Solution\n\nRefPedia integrates five learning modules:\n\nModule	What It Does\n📹 Video Lessons	Curated tutorials on rules, fouls, and signals.\n🎬 Video Quiz	Identify calls from real game footage; typo-tolerant answers.\n✋ Hand Signal Recognition	Image-based quiz with automatic retry for wrong answers.\n📷 Camera Practice	Perform hand signals via camera, review, redo, and confirm.\n📝 Theoretical Exam	True/False practice or timed exam (30 min, 80% pass).\nKey Features\nAuthentication: Email/password or Google Sign-In, with Guest mode.\nUser Profile: Update credentials and submit feedback.\nNotifications: In-app system synced via Firebase.\nAdmin Panel: Add/edit questions, manage feedback, moderate content.\nAI Moderation: Gemini 1.5 Flash filters toxic/off-topic feedback automatically.\nUser Flow\nWelcome\n ├─ Sign Up → Home\n ├─ Login → Home\n └─ Guest → Home\n\nHome\n ├─ Learn (Video Lessons)\n ├─ Recognise Hand Signals\n ├─ Practice Hand Signals (Camera)\n ├─ Video Test\n ├─ Theoretical Exam\n ├─ Notifications\n └─ Profile (Update, Feedback, Logout)\nAudience & Platforms\nUsers: Basketball referees, instructors, and enthusiasts.\nPlatforms: iOS ✅ | Android ✅ ", 7);
    addNode(109, "RefPedia_documantation", "txt", "4.0 K", "2026-03-21", "RefPedia — Technical Overview\nTech Stack\nFrontend: React Native (Expo), JavaScript (ES2020+)\nRouting: Expo Router (file-based navigation)\nBackend: Firebase (Authentication, Firestore, Storage)\nAI Moderation: Google Gemini API\nMedia: expo-video / expo-av (video), expo-camera\nStorage: AsyncStorage (local), Firestore (cloud)\nArchitecture\n\nRefPedia follows a modular, component-based architecture with clear separation between UI, logic, and services.\n\nApp Layer: File-based routing with dedicated screens (auth, learning, quizzes, profile, feedback)\nComponents: Reusable UI elements (buttons, inputs, layouts)\nServices: Firebase integration and user data handling\nState Management: React Context (AuthProvider)\nCore Features\nAuthentication: Email/password + Google Sign-In (OAuth)\nLearning System: Video lessons and interactive quizzes\nPractice Mode: Camera-based hand signal training\nExams: Timed and practice theoretical tests\nFeedback System: Admin/user roles with AI moderation\nNotifications: In-app messaging system\nDatabase Design (Firestore)\n\nKey collections:\n\nusers → roles (admin/user)\nenunturi → quiz questions (true/false)\ncamera → practice tasks\nfeedback → user feedback + replies\nmessages → notifications\nSecurity\nFirebase Authentication for user management\nRole-based access control (admin vs user)\nAI-powered content moderation (Gemini API)\nSecure data handling via Firebase rules\nDesign System\nResponsive UI: Custom hp/wp scaling functions\nConsistent Styling: Centralized theme (colors, typography, spacing)\nMobile-first UX: Optimized for clarity and usability", 7);
    addNode(110, "RefPedia_terms&conditions.txt", "txt", "4.0 K", "2026-03-21", "By using RefPedia, you agree to these terms.\nEffective / Last Updated: March 21, 2026\n\n1. Use of the App\nRefPedia is an educational tool for learning basketball refereeing. It is intended for personal, non-commercial use only. You agree to use the app responsibly and in accordance with applicable laws.\n\n2. Accounts & Access\nSome features require an account. You are responsible for keeping your login details secure. Guest mode offers limited access without registration.\n\n3. Content & Intellectual Property\nAll app content (videos, quizzes, design, etc.) is protected and may not be copied or reused without permission. Basketball rules themselves remain public domain.\n\n4. User Conduct\nYou agree not to misuse the app, attempt unauthorized access, or submit harmful, offensive, or irrelevant content.\n\n5. Data & Privacy\nWe collect minimal data (email, app usage, feedback). We do not collect sensitive data such as photos (stored locally only) or location data. Services like Firebase and Google Sign-In may process data according to their policies.\n\n6. Feedback & Moderation\nUser feedback may be moderated automatically. Inappropriate content may be removed.\n\n7. Disclaimer\nThe app is provided “as is” without guarantees of accuracy or availability. RefPedia does not provide official certification.\n\n8. Liability\nWe are not responsible for any damages resulting from the use of the app.\n\n9. Changes\nTerms may be updated at any time. Continued use means you accept the changes.\n\n10. Contact\nmihai.arisanu2006@gmail.com", 7);
    addNode(111, "RefPedia_googleplay.sh", "exec", "4.0 K", "2026-03-21", "https://play.google.com/store/apps\nUnfortunately the application is not launched yet. \nFollow my Linkedin page to stay up to date with the launch of this \napplication and many other interesting projects.", 7);
    addNode(112, "RefPedia_appstore.sh", "exec", "4.0 K", "2026-03-21", "https://apps.apple.com/ro/iphone/today?l=ro\nUnfortunately the application is not launched yet. \nFollow my Linkedin page to stay up to date with the launch of this \napplication and many other interesting projects.", 7);
    addNode(113, "RefPedia_github.sh", "exec", "4.0 K", "2026-03-21", "https://github.com/mihaiarisanu/RefPedia", 7);
    addNode(114, "NightDrive_presentation.txt", "txt", "4.0 K", "2026-03-21", "NightDrive — App Overview\n\nNightDrive is a real-time, community-driven navigation app for car enthusiasts who value the experience of driving as much as the destination. Featuring a sleek OLED-friendly dark UI and social hazard reporting, it redefines night driving.\n\n\"Navigate the night. Own the road.\"\n\nThe Challenge\n\nTraditional GPS apps focus only on routes and shortest paths, lacking interactivity, social connection, and night-optimized design.\n\nOur Solution\n\nNightDrive integrates navigation, community, and social features:\n\nFeature	What It Does\nNight-Mode Navigation:\n	OLED-friendly dark maps with live GPS, speed, and heading. Cinematic camera tilt above 5 km/h.\nSmart Routing:\n	Turn-by-turn directions with dead-reckoning for GPS loss and auto-rerouting.\nReal-Time Event Reporting:\n	Community-reported hazards (accidents, police, potholes) with upvote validation.\nDriver Network:\n	Unique hex tags, friend requests, and in-app messaging.\nSecure Authentication:\n	JWT sessions, Bcrypt password hashing, persistent login.\nSaved Places & Preferences:\n	Bookmark destinations, avoid disliked streets, save favorite routes.\nProfile Management:\n	Edit profile, change avatar/email, delete account GDPR-compliantly.\n\nDesign Philosophy\nOLED-First: Pure black backgrounds for eye comfort and battery savings.\nNeon Accents: Purple highlights for a cyberpunk feel.\nMinimalist HUD: Essential info within thumb reach.\nGlassmorphism: Floating translucent bars for modern aesthetic.\nZero UI Clutter: Focus on the road, hide unnecessary overlays.\nUser Flow:\nWelcome → Login/Register → Main Map\n           					↘ Menu → Profile / Friends / Saved Places / Events\nArchitecture\nClient: React Native (TypeScript)\nBackend: Go (REST API)\nDatabase: PostgreSQL + PostGIS\nReal-Time: WebSocket support for live updates\nAuth: JWT + Bcrypt\nDeployment: Docker Compose (Client + API + DB)\nWhy NightDrive Stands Out\nAspect	Traditional GPS	NightDrive\nDesign	Bright, generic UI	OLED-dark, cyberpunk style\nCommunity	Passive	Active social cruising\nHazards	Limited	Night-focused, verified\nGPS Loss	Freezes	Dead-reckoning simulation\nIdentity	Email/Name	Unique hex tag\nRoad Preferences	None	Avoid disliked streets\nTarget Users\nNight drivers & urban commuters\nCar enthusiasts & social cruisers\nDrivers who want real-time hazard alerts\nRoadmap\nLive friend tracking\nGroup cruises & coordinated drives\nLeaderboards for verified reporting\nVoice alerts for hands-free safety\nAI-based road quality scoring\n\nNightDrive — Navigate the night. Own the road. 🌙", 8);
    addNode(115, "NightDrive_documentation", "txt", "4.0 K", "2026-03-21", "NightDrive — Technical Overview\n\nNightDrive is a real-time, community-driven night navigation app. Built with React Native, Go, and PostgreSQL/PostGIS, it emphasizes immersive night driving, social connectivity, and hazard reporting.\n\nArchitecture\n\nMonorepo structure with three core services orchestrated via Docker Compose:\n\nClient (React Native)  ↔  Backend API (Go)  ↔  PostgreSQL + PostGIS\n     Port:8081             Port:8080            Port:5432\nCommunication: RESTful JSON + WebSocket (real-time events)\nDeployment: Docker Compose (frontend + backend + DB)\nTechnology Stack\nLayer	Technology\nClient	React Native (TypeScript), React Navigation, Google Maps SDK, AsyncStorage, Hooks for GPS & dead reckoning\nBackend	Go (Golang), net/http, JWT auth, Bcrypt password hashing\nDatabase	PostgreSQL 15 + PostGIS 3.4 (spatial queries)\nContainerization	Docker Compose\nProject Structure (Simplified)\nnightdrive-main/\n├── client/      # React Native app\n├── api/         # Go backend\n├── docker-compose.yml\n\nClient Highlights:\n\nMainScreen.tsx — Map, real-time location, dead reckoning, event reporting\nMenuScreen.tsx — Profile, friends, saved places, disliked streets\nCustom hooks: useLocation, useDeadReckoning, useRerouting\n\nBackend Highlights:\n\nEndpoints: /users, /login, /me, /events, /friends, /ws\nHandlers: User management, event creation, vote handling, WebSocket updates\nModels: User, Event\nCore Features\nNavigation & Spatial\nGPS tracking with speed & heading\nDead reckoning simulation during GPS loss\nAuto-rerouting if deviation > 50m\nSpatial queries via PostGIS (ST_DWithin)\nEvent Reporting\nTypes: Accident, Police, Hazard, Roadworks\nCommunity upvote/downvote validation\nAutomatic expiration after timestamp\nSocial System\nUnique 4-character hex tags (#4Z9C) for identity\nFriend requests: search by tag, accept/reject, store friendships\nAuthentication\nJWT tokens (72-hour expiry)\nPassword hashing with Bcrypt\nPersistent storage in AsyncStorage\nDatabase Schema (Highlights)\nTable	Purpose\nusers	User profiles with tags, points, trust score\nevents	Geo-located reports with upvotes/downvotes\nfriend_requests	Pending friend requests\nfriendships	Established friendships (ordered to prevent duplicates)\nsaved_routes	User-saved routes with start/end points\nDeployment & Env Variables\n\nDocker Compose services:\n\ndb: PostgreSQL + PostGIS\nnightdrive-backend: Go API\nnightdrive-frontend: React Native\n\nQuick start:\n\ndocker-compose up --build\n\nKey environment variables:\n\nAPI_BASE_URL, GOOGLE_API_GENERAL_KEY (client)\nDB_USER, DB_PASSWORD, DB_NAME, DB_HOST, DB_PORT (backend)", 8);
    addNode(116, "NightDrive_terms&conditions.txt", "txt", "4.0 K", "2026-03-21", "NightDrive — Terms & Conditions\n\nEffective / Last Updated: March 21, 2026\n\nNightDrive is a community-driven navigation app for car enthusiasts, providing real-time GPS navigation, social features, and crowd-sourced road event reporting. By using the App, users agree to comply with these Terms.\n\n1. User Eligibility & Accounts\nMust be ≥18 years old or legal driving age.\nValid driver’s license required if using while driving.\nAccount creation requires email, username, password, and generates a unique driver tag (e.g., #4Z9C).\nUsers are responsible for account security. Account deletion permanently removes data and friend connections.\n2. Acceptable Use\n\nUsers must:\n\nFollow traffic laws and report accurate road events.\nTreat other users respectfully.\n\nProhibited activities:\n\nUnsafe interaction while driving.\nFalse reports or vote manipulation.\nUnauthorized access, impersonation, or automated scraping.\n3. Driving Safety Disclaimer\nNightDrive is informational only; the driver is always responsible.\nGPS, dead reckoning, and community reports may contain errors.\nDo not use App features as a substitute for vehicle instruments.\nNightDrive and affiliates are not liable for accidents, fines, or damages.\n4. Community Content\nUsers are responsible for accuracy and legality of reports.\nEvent upvote/downvote system helps validate content but is not guaranteed.\nNightDrive may remove content violating Terms.\n5. Intellectual Property & Licensing\nApp code, design, logos, and brand are owned by NightDrive.\nLimited, personal-use license granted to users.\nThird-party services (Google Maps, PostGIS) are subject to their own terms.\n6. Privacy & Data\n\nCollected Data:\n\nAccount (email, username, tag, password hash)\nLocation (GPS) during active navigation\nUsage data (events, votes, friends, saved places)\nDevice info\n\nUsage: To provide navigation, social, and event features.\n\nSecurity:\n\nPasswords hashed via bcrypt\nAPI calls secured with JWT tokens\nEncrypted transmission\n\nSharing: Only with law enforcement, legal process, or essential service providers.\n\nUser Rights: Access, correct, delete, export data; withdraw consent at any time.\n\n7. Liability & Indemnification\nApp is provided “as is”; no warranties.\nNightDrive not liable for indirect, incidental, or consequential damages.\nUsers indemnify NightDrive for claims arising from misuse or illegal activity.\n8. Termination\nUsers can delete accounts anytime.\nNightDrive may suspend accounts for violations or malicious activity.\nLiability, IP, and indemnification clauses survive termination.\n9. Modifications & Governing Law\nTerms may be updated; continued use = acceptance.\nGoverned by Romanian law, jurisdiction of Bucharest courts.\n10. Contact\nEmail: mihai.arisanu2006@gmail.com", 8);
    addNode(117, "NightDrive_googleplay.sh", "exec", "4.0 K", "2026-03-21", "https://play.google.com/store/apps\nUnfortunately the application is not launched yet. \nFollow my Linkedin page to stay up to date with the launch of this \napplication and many other interesting projects.", 8);
    addNode(118, "NightDrive_appstore.sh", "exec", "4.0 K", "2026-03-21", "https://apps.apple.com/ro/iphone/today?l=ro\nUnfortunately the application is not launched yet. \nFollow my Linkedin page to stay up to date with the launch of this \napplication and many other interesting projects.", 8);
    addNode(119, "NightDrive_github.sh", "exec", "4.0 K", "2026-03-21", "https://github.com/mihaiarisanu/Nightdrive", 8);
    addNode(120, "download_cv.exe", "exec", "4.0 K", "2026-03-21", "", 0);
    addNode(121, "Portofolio_descriere", "txt", "4.0 K", "2026-03-21", "A web portfolio is more than just a digital resume; it's an opportunity to express your mindset and personality through code. Instead of relying on bloated modern frameworks, I chose to build this portfolio from scratch—engineering a custom terminal operating system powered by a C++ kernel and WebAssembly. No excess, no distractions.", 9);
    addNode(122, "Portofolio_documentation", "txt", "4.0 K", "2026-03-21", "MihaiArisanuOS\n\nA custom, interactive terminal-based portfolio simulating a lightweight Operating System directly in the browser. Built with a unique architecture that bridges a modern Headless CMS with a custom C++ kernel compiled to WebAssembly (WASM).\n\nArchitecture\nUnlike traditional React portfolios, MaOS separates the core logic from the UI:\n\nFrontend (UI): React + Vite. Handles terminal rendering, keyboard inputs, and visual animations.\n\nKernel & Virtual File System (VFS): C++. Manages the file hierarchy, navigation logic, and state. Compiled to WebAssembly for near-native performance.\n\nBackend / CMS: Sanity.io. Acts as the single source of truth for all content (files, directories, links, bio).\n\n🚀 How It Works (The Data Pipeline)\nTo maintain maximum performance without querying a database on every render, the project uses a custom build pipeline:\n\nContent is written and managed in Sanity CMS.\n\nA custom Node.js script (generateVFS.mjs) fetches the structured data via Sanity's API.\n\nThe script automatically writes the C++ code (vfs.cpp), injecting the content directly into the memory structure of the C++ Kernel.\n\nThe C++ code is compiled via Emscripten into core.wasm and core.js.\n\nReact mounts the WASM module and interacts with the engine instantly.\n\nTech Stack\nUI: React, Vite, CSS (Custom Terminal Aesthetics)\n\nCore Logic: C++, WebAssembly (WASM), Emscripten\n\nContent Management: Sanity.io, Node.js, @sanity/client", 9);
    addNode(123, "Portofolio_github.sh", "exec", "4.0 K", "2026-03-21", "https://github.com/MihaiArisanu/WebPortofolio", 9);
    addNode(124, "awards.txt", "txt", "4.0 K", "2026-03-21", "• First place HardcoreEntrepreneur - 2025 (https://he.upb.ro/)\n• Honourable mention at national stage of Olympiad of Scientific Creativity - Information Technology category 2024\n• 3rd place at County Olympiad of Artificial Intelligence - 2025\n• Second place at county stage of Inovation and Digital Creativity Olympiad \"InfoEducatie\" - Educational Software category 2025\n• Bronze medal at national stage of Olympiad of Scientific Creativity - Information Technology category 2024\n• 3rd place at the county stage and partcipation at national stage of European Statistics Competition 2024\n• Special Award at Hardcore Entrepreneur 4.0 2024\n• 1st place at County Olympiad of Scientific Creativity - Information Technology category and participation at national stahe 2024\n• 2nd place at the Information Technology County Olympiad - C# category 2024\n• 3rd place at the county stage of Innovation and Digital Creativity Olympiad \"InfoEducatie\" - Utility/Mobile Software category 2024\nSpecial Award at Hardcore Entrepreneur 3.0 2023\n• Honourable mention at National Olympiad of Scientific Creativity - Information Technology category 2023\n• 1st place at County Olympiad of Scientific Creativity - Information Technology category 2023\n• 1st place at County Information Technology Olympiad - IT&C category 2023\nHonourable mention at County Computer Science Olympiad 2023\n• 3rd place at the national stage of Innovation and Digital Creativity Olympiad \"InfoEducatie\" - Educational Software category 2021", 5);
    addNode(125, "ActForGreenfootItaly.txt", "txt", "4.0 K", "2026-03-21", "Act for Greenfoot, Not Global Warming – Pontassieve, Italy | 1 week | 2022\n        • Collaborated with students from Romania, Italy, Turkey, and Greece\n        • Participated in environmental awareness workshops and sustainability activities\n        • Developed teamwork and intercultural communication skills\n\nOrganization: Istituto Comprensivo di PONTASSIEVE", 12);
    addNode(126, "SportsTrainingGreece.txt", "txt", "4.0 K", "2026-03-21", "Sports Vocational Training – Thessaloniki, Greece | 3 weeks | 2023\n        • Trained under an Olympic athletics coach in a sport outside my usual expertise\n        • Learned new techniques, discipline, and adaptability in a high-performance environment\n        • Gained insight into international sports training and coaching methods\n\nOrganization: Education Organization IPODOMI", 12);
    addNode(127, "ClimateActionCyprus.txt", "txt", "4.0 K", "2026-03-21", "From Do Nothing to Do Something for Climate – Cyprus | 1 week\n        • Engaged with peers from Cyprus, Romania, Czech Republic, Greece, and Lithuania\n        • Organized and participated in climate action initiatives\n        • Strengthened leadership, collaboration, and problem-solving skills\n\nOrganization: Harmania Youth Network", 12);
    addNode(128, "basketball.txt", "txt", "4.0 K", "2026-03-21", "Semi-Pro Basketball Player – Division B, Romania | 2 seasons\n            • Competed at semi-professional level\n            • Developed teamwork, discipline, time management", 10);
    addNode(129, "table_official&statistician.txt", "txt", "4.0 K", "2026-03-21", "FIBA Table Official & Statistician – FIBA, International | 2024 - present\n            • Officiated domestic and international games\n            • Managed game timing, scorekeeping, and statistics\n            • Ensured compliance with official basketball rules", 10);
    addNode(130, "CTF_organizer.txt", "txt", "4.0 K", "2026-03-21", "- Organized first city-wide CTF event in Râmnicu Vâlcea (volunteer)\n- Collaborated with team under Project IVI and hashtag#UNbreakableRomania\n- Configured network, designed challenges, and ensured smooth execution\n- Explored reverse engineering, cryptography, pwn, and foundational CTF theory\n- Strengthened teamwork, organizational, and results-oriented skills\n\nLinkedIn post: https://www.linkedin.com/feed/update/urn:li:activity:7440851918542802944/", 11);
    addNode(131, "ProjectIVI_course.txt", "txt", "4.0 K", "2026-03-21", "IT Infrastructure course at Project IVI, Râmnicu Vâlcea\n- Covered CCNA 1 & 2 (network fundamentals, routing, switching)\n- Introduction to Linux: explored system internals and discovered passion for low-level computing\n- Developed basic automation scripts using Bash and Python\n- Gained hands-on experience in configuring networks, managing Linux systems, and automating tasks\n\nProjectIVI website: https://projectivi.ro/", 4);
    addNode(132, "EuropeDirect_volunteer.txt", "txt", "4.0 K", "2026-03-21", "- Participated in local EuropeDirect volunteer association\n- Promoted events and initiatives for city residents\n- Engaged with citizens to raise awareness about EU programs\n\nLink to Facebook page: https://www.facebook.com/europedirectvl/?locale=ro_RO\nLink to EuropeDirect website: https://www.cicvalcea.ro/", 11);
}

int VFS::addNode(int id, std::string name, std::string type, std::string size, std::string date, std::string content, int parent_id) {
    FileNode node;
    node.id = id;
    node.name = name;
    node.type = type;
    node.size = size;
    node.date = date;
    node.content = content;
    node.parent_id = parent_id;

    nodes.push_back(node);

    if (parent_id != -1) {
        for (auto& p : nodes) {
            if (p.id == parent_id && p.type == "dir") {
                p.children_ids.push_back(node.id);
                break;
            }
        }
    }
    return node.id;
}

const FileNode* VFS::getNode(int id) const {
    for (const auto& node : nodes) {
        if (node.id == id) return &node;
    }
    return nullptr;
}

std::vector<int> VFS::getDirectoryContents(int dir_id) const {
    const FileNode* dir = getNode(dir_id);
    if (dir && dir->type == "dir") {
        return dir->children_ids;
    }
    return {};
}
