#include "vfs.h"

VFS::VFS() {
    addNode(0, "root", "dir", "4.0 K", "2026-03-21", "", -1);
    addNode(1, "about", "dir", "4.0 K", "2026-03-21", "", 0);
    addNode(2, "projects", "dir", "4.0 K", "2026-03-21", "", 0);
    addNode(3, "experience", "dir", "4.0 K", "2026-03-21", "", 0);
    addNode(4, "education", "dir", "4.0 K", "2026-03-21", "", 0);
    addNode(5, "certification&awards", "dir", "4.0 K", "2026-03-21", "", 0);
    addNode(6, "social", "dir", "4.0 K", "2026-03-21", "", 0);
    addNode(7, "RefPedia", "dir", "4.0 K", "2026-03-21", "", 2);
    addNode(8, "NightDrive", "dir", "4.0 K", "2026-03-21", "", 2);
    addNode(9, "portofolio", "dir", "4.0 K", "2026-03-21", "", 2);
    addNode(10, "jobs", "dir", "4.0 K", "2026-03-21", "", 3);
    addNode(11, "community", "dir", "4.0 K", "2026-03-21", "", 3);
    addNode(12, "Erasmus", "dir", "4.0 K", "2026-03-21", "", 3);
    addNode(101, "bio.txt", "txt", "4.0 K", "2026-03-21", "Hi, I’m Mihai Arisanu, a final-year high school student with a strong interest in computer science. I’m a creative and collaborative person who enjoys working in team environments and contributing to shared goals.\n\nI’m particularly passionate about low-level programming, while also developing practical mobile applications designed to improve everyday life.\n\nOutside of tech, I enjoy playing basketball and following the game whenever I can.", 1);
    addNode(102, "career_stats.txt", "txt", "4.0 K", "2026-03-21", "=========================================\nPLAYER STATS: MIHAI ARISANU\n\nPOSITION : Final-Year of Highschool Student\nPLAY STYLE : Takes on any challenge & thrives in problem-solving\nTECH STACK : C++, JavaScript, Mobile Development\nSIGNATURE MOVE : Building efficient, real-world applications\n\nBONUS TRAIT : Creative team player with a passion for collaboration\nOFF COURT : Basketball enthusiast (player & fan)", 1);
    addNode(103, "les_patachous.txt", "txt", "4.0 K", "2026-03-21", "Volunteering at kindergarten \"Les Patachous\", Bassecourt Switzerland | 2 weeks\n            • Assisted staff with daily activities\n            • Supported child development activities\n\nLink to their website: https://mehs.ch/les-patachous/presentation/", 11);
    addNode(104, "highschool.txt", "txt", "4.0 K", "2026-03-21", "High School Education (2022–2026)\nMircea cel Bătrân National College, Rm. Vâlcea, Romania\n\nKey Skills & Knowledge Acquired:\n\n- C++ Programming:\n    • Algorithmic thinking and problem-solving\n    • Data structures: vectors, matrices\n    • Basics of graphs, dynamic programming, and greedy algorithms\n\n- Machine Learning Foundations:\n    • Data manipulation and analysis in Python\n    • Applied basic ML algorithms:\n        - Linear Regression\n        - Logistic Regression\n        - k-Nearest Neighbors (k-NN)\n        - Random Forest", 4);
    addNode(105, "certifications.txt", "txt", "4.0 K", "2026-03-21", "IELTS band 7 (CEFR: C1)\nFIBA (International Basketball Federation) International Table Official Certification\nIC3", 5);
    addNode(106, "github.sh", "exec", "4.0 K", "2026-03-21", "https://github.com/MihaiArisanu", 6);
    addNode(107, "linkedin.sh", "exec", "4.0 K", "2026-03-21", "https://www.linkedin.com/in/mihai-arisanu-4999452a5/", 6);
    addNode(108, "RefPedia_presentation.txt", "txt", "4.0 K", "2026-03-21", "RefPedia — App Overview\n\nRefPedia is a mobile app (iOS & Android) for basketball referees to learn, practice, and test their skills in one place (videos, quizzes, camera exercises, exams).\n\nProblem: Traditional training is slow, rigid, and non-interactive.\nSolution: 5 integrated learning modules:\n\n📹 Video lessons (rules, fouls, signals)\n🎬 Video quiz (real game scenarios)\n✋ Hand signal recognition (image-based quiz)\n📷 Camera practice (perform signals)\n📝 Theoretical exam (practice or timed)\n\nKey Features:\n\nAuthentication (email, Google, Guest)\nUser profile + feedback\nIn-app notifications\nAdmin panel (content management)\nAI moderation (Gemini)\n\nUser Flow: Login/Signup/Guest → Home → learning & testing modules\n\nAudience: referees, instructors, basketball enthusiasts\nPlatforms: iOS & Android", 7);
    addNode(109, "RefPedia_documantation", "txt", "4.0 K", "2026-03-21", "RefPedia — Technical Overview\n\nTech Stack: React Native (Expo), Expo Router, Firebase (Auth, Firestore, Storage), Google Gemini API, expo-video/av, expo-camera, AsyncStorage\n\nArchitecture: Modular, component-based (UI, logic, services)\n\nApp: file-based screens (auth, learning, quizzes, profile)\nComponents: reusable UI\nServices: Firebase integration\nState: React Context\n\nCore Features:\n\nAuth (email + Google)\nLearning (video + quizzes)\nPractice (camera-based)\nExams (timed/tests)\nFeedback (AI moderation)\nNotifications\n\nDatabase (Firestore): users, enunturi, camera, feedback, messages\n\nSecurity: Auth, role-based access, AI moderation, Firebase rules\n\nDesign: Responsive UI, centralized theme, mobile-first UX", 7);
    addNode(110, "RefPedia_terms&conditions.txt", "txt", "4.0 K", "2026-03-21", "By using RefPedia, you agree to these terms.\nEffective / Last Updated: March 21, 2026\n\n1. Use of the App\nRefPedia is an educational tool for learning basketball refereeing. It is intended for personal, non-commercial use only. You agree to use the app responsibly and in accordance with applicable laws.\n\n2. Accounts & Access\nSome features require an account. You are responsible for keeping your login details secure. Guest mode offers limited access without registration.\n\n3. Content & Intellectual Property\nAll app content (videos, quizzes, design, etc.) is protected and may not be copied or reused without permission. Basketball rules themselves remain public domain.\n\n4. User Conduct\nYou agree not to misuse the app, attempt unauthorized access, or submit harmful, offensive, or irrelevant content.\n\n5. Data & Privacy\nWe collect minimal data (email, app usage, feedback). We do not collect sensitive data such as photos (stored locally only) or location data. Services like Firebase and Google Sign-In may process data according to their policies.\n\n6. Feedback & Moderation\nUser feedback may be moderated automatically. Inappropriate content may be removed.\n\n7. Disclaimer\nThe app is provided “as is” without guarantees of accuracy or availability. RefPedia does not provide official certification.\n\n8. Liability\nWe are not responsible for any damages resulting from the use of the app.\n\n9. Changes\nTerms may be updated at any time. Continued use means you accept the changes.\n\n10. Contact\nmihai.arisanu2006@gmail.com", 7);
    addNode(111, "RefPedia_googleplay.sh", "exec", "4.0 K", "2026-03-21", "https://play.google.com/store/apps\nUnfortunately the application is not launched yet. \nFollow my Linkedin page to stay up to date with the launch of this \napplication and many other interesting projects.", 7);
    addNode(112, "RefPedia_appstore.sh", "exec", "4.0 K", "2026-03-21", "https://apps.apple.com/ro/iphone/today?l=ro\nUnfortunately the application is not launched yet. \nFollow my Linkedin page to stay up to date with the launch of this \napplication and many other interesting projects.", 7);
    addNode(113, "RefPedia_github.sh", "exec", "4.0 K", "2026-03-21", "https://github.com/mihaiarisanu/RefPedia", 7);
    addNode(114, "NightDrive_presentation.txt", "txt", "4.0 K", "2026-03-21", "NightDrive — App Overview\n\nNightDrive is a real-time, community-driven navigation app for night drivers and car enthusiasts, combining navigation, social features, and hazard reporting in a sleek dark UI.\n\nProblem: Traditional GPS apps lack interactivity, social features, and night-optimized design.\nSolution: Integrated navigation + community platform:\n\n🌙 Night-mode navigation (dark UI, live GPS, speed, heading)\n🧭 Smart routing (turn-by-turn, dead reckoning, auto-reroute)\n⚠️ Real-time hazard reporting (community-verified)\n👥 Social system (hex tags, friends, messaging)\n🔐 Secure auth (JWT, Bcrypt)\n⭐ Saved places & route preferences\n\nDesign: OLED-dark, minimalist, neon-accented, distraction-free\n\nUser Flow: Login/Register → Map → Menu (profile, friends, saved, events)\n\nTech: React Native + Go + PostgreSQL/PostGIS + WebSockets + Docker\n\nWhy it stands out:\n\nNight-optimized UI\nActive community reporting\nWorks during GPS loss\nUnique identity system (hex tags)\nCustom route preferences\n\nTarget users: night drivers, commuters, car enthusiasts\n\nFuture: friend tracking, group drives, leaderboards, voice alerts, AI road scoring\n\nTagline: Navigate the night. Own the road. 🌙", 8);
    addNode(115, "NightDrive_documentation", "txt", "4.0 K", "2026-03-21", "NightDrive — Technical Overview\n\nNightDrive is a real-time, community-driven night navigation app built with React Native, Go, and PostgreSQL/PostGIS, focused on navigation, social features, and hazard reporting.\n\nArchitecture:\nMonorepo with 3 services (Docker Compose):\nClient (React Native) ↔ Backend (Go API) ↔ Database (PostgreSQL + PostGIS)\nCommunication: REST + WebSocket (real-time)\n\nTech Stack:\n\nClient: React Native (TypeScript), Google Maps, AsyncStorage\nBackend: Go, JWT auth, Bcrypt\nDatabase: PostgreSQL + PostGIS\nDeployment: Docker Compose\n\nCore Features:\n\nGPS tracking + dead reckoning + auto-rerouting\nEvent reporting (accidents, police, hazards, roadworks)\nCommunity voting & auto-expiration\nSocial system (friend tags, requests)\nAuthentication (JWT, secure passwords)\n\nBackend:\nEndpoints for users, events, friends, WebSocket updates\n\nDatabase:\nUsers, events, friendships, friend requests, saved routes\n\nDeployment:\nDockerized (frontend, backend, DB)\nRun with: docker-compose up --build\n\nConfig:\nEnv vars for API, Google Maps key, and database credentials", 8);
    addNode(116, "NightDrive_terms&conditions.txt", "txt", "4.0 K", "2026-03-21", "NightDrive — Terms & Conditions\n\nEffective / Last Updated: March 21, 2026\n\nNightDrive is a community-driven navigation app for car enthusiasts, providing real-time GPS navigation, social features, and crowd-sourced road event reporting. By using the App, users agree to comply with these Terms.\n\n1. User Eligibility & Accounts\nMust be ≥18 years old or legal driving age.\nValid driver’s license required if using while driving.\nAccount creation requires email, username, password, and generates a unique driver tag (e.g., #4Z9C).\nUsers are responsible for account security. Account deletion permanently removes data and friend connections.\n2. Acceptable Use\n\nUsers must:\n\nFollow traffic laws and report accurate road events.\nTreat other users respectfully.\n\nProhibited activities:\n\nUnsafe interaction while driving.\nFalse reports or vote manipulation.\nUnauthorized access, impersonation, or automated scraping.\n3. Driving Safety Disclaimer\nNightDrive is informational only; the driver is always responsible.\nGPS, dead reckoning, and community reports may contain errors.\nDo not use App features as a substitute for vehicle instruments.\nNightDrive and affiliates are not liable for accidents, fines, or damages.\n4. Community Content\nUsers are responsible for accuracy and legality of reports.\nEvent upvote/downvote system helps validate content but is not guaranteed.\nNightDrive may remove content violating Terms.\n5. Intellectual Property & Licensing\nApp code, design, logos, and brand are owned by NightDrive.\nLimited, personal-use license granted to users.\nThird-party services (Google Maps, PostGIS) are subject to their own terms.\n6. Privacy & Data\n\nCollected Data:\n\nAccount (email, username, tag, password hash)\nLocation (GPS) during active navigation\nUsage data (events, votes, friends, saved places)\nDevice info\n\nUsage: To provide navigation, social, and event features.\n\nSecurity:\n\nPasswords hashed via bcrypt\nAPI calls secured with JWT tokens\nEncrypted transmission\n\nSharing: Only with law enforcement, legal process, or essential service providers.\n\nUser Rights: Access, correct, delete, export data; withdraw consent at any time.\n\n7. Liability & Indemnification\nApp is provided “as is”; no warranties.\nNightDrive not liable for indirect, incidental, or consequential damages.\nUsers indemnify NightDrive for claims arising from misuse or illegal activity.\n8. Termination\nUsers can delete accounts anytime.\nNightDrive may suspend accounts for violations or malicious activity.\nLiability, IP, and indemnification clauses survive termination.\n9. Modifications & Governing Law\nTerms may be updated; continued use = acceptance.\nGoverned by Romanian law, jurisdiction of Bucharest courts.\n10. Contact\nEmail: mihai.arisanu2006@gmail.com", 8);
    addNode(117, "NightDrive_googleplay.sh", "exec", "4.0 K", "2026-03-21", "https://play.google.com/store/apps\nUnfortunately the application is not launched yet. \nFollow my Linkedin page to stay up to date with the launch of this \napplication and many other interesting projects.", 8);
    addNode(118, "NightDrive_appstore.sh", "exec", "4.0 K", "2026-03-21", "https://apps.apple.com/ro/iphone/today?l=ro\nUnfortunately the application is not launched yet. \nFollow my Linkedin page to stay up to date with the launch of this \napplication and many other interesting projects.", 8);
    addNode(119, "NightDrive_github.sh", "exec", "4.0 K", "2026-03-21", "https://github.com/mihaiarisanu/Nightdrive", 8);
    addNode(120, "download_cv.exe", "exec", "4.0 K", "2026-03-21", "", 0);
    addNode(121, "Portofolio_descriere", "txt", "4.0 K", "2026-03-21", "A web portfolio is more than just a digital resume; it's an opportunity to express your mindset and personality through code. Instead of relying on bloated modern frameworks, I chose to build this portfolio from scratch—engineering a custom terminal operating system powered by a C++ kernel and WebAssembly. No excess, no distractions.", 9);
    addNode(122, "Portofolio_documentation", "txt", "4.0 K", "2026-03-21", "MihaiArisanuOS\n\nA custom, interactive terminal-based portfolio simulating a lightweight Operating System directly in the browser. Built with a unique architecture that bridges a modern Headless CMS with a custom C++ kernel compiled to WebAssembly (WASM).\n\nArchitecture\nUnlike traditional React portfolios, MaOS separates the core logic from the UI:\n\nFrontend (UI): React + Vite. Handles terminal rendering, keyboard inputs, and visual animations.\n\nKernel & Virtual File System (VFS): C++. Manages the file hierarchy, navigation logic, and state. Compiled to WebAssembly for near-native performance.\n\nBackend / CMS: Sanity.io. Acts as the single source of truth for all content (files, directories, links, bio).\n\n🚀 How It Works (The Data Pipeline)\nTo maintain maximum performance without querying a database on every render, the project uses a custom build pipeline:\n\nContent is written and managed in Sanity CMS.\n\nA custom Node.js script (generateVFS.mjs) fetches the structured data via Sanity's API.\n\nThe script automatically writes the C++ code (vfs.cpp), injecting the content directly into the memory structure of the C++ Kernel.\n\nThe C++ code is compiled via Emscripten into core.wasm and core.js.\n\nReact mounts the WASM module and interacts with the engine instantly.\n\nTech Stack\nUI: React, Vite, CSS (Custom Terminal Aesthetics)\n\nCore Logic: C++, WebAssembly (WASM), Emscripten\n\nContent Management: Sanity.io, Node.js, @sanity/client", 9);
    addNode(123, "Portofolio_github.sh", "exec", "4.0 K", "2026-03-21", "https://github.com/MihaiArisanu/WebPortofolio", 9);
    addNode(124, "awards.txt", "txt", "4.0 K", "2026-03-21", "• 1st place at HardcoreEntrepreneur - 2025 (https://he.upb.ro/)\n• Honourable mention at national stage of Olympiad of Scientific Creativity - Information Technology category 2024\n• 3rd place at County Olympiad of Artificial Intelligence - 2025\n• 2nd place at county stage of Inovation and Digital Creativity Olympiad \"InfoEducatie\" - Educational Software category 2025\n• Bronze medal at national stage of Olympiad of Scientific Creativity - Information Technology category 2024\n• 3rd place at the county stage and partcipation at national stage of European Statistics Competition 2024\n• Special Award at Hardcore Entrepreneur 4.0 2024\n• 1st place at County Olympiad of Scientific Creativity - Information Technology category and participation at national stahe 2024\n• 2nd place at the Information Technology County Olympiad - C# category 2024\n• 3rd place at the county stage of Innovation and Digital Creativity Olympiad \"InfoEducatie\" - Utility/Mobile Software category 2024\nSpecial Award at Hardcore Entrepreneur 3.0 2023\n• Honourable mention at National Olympiad of Scientific Creativity - Information Technology category 2023\n• 1st place at County Olympiad of Scientific Creativity - Information Technology category 2023\n• 1st place at County Information Technology Olympiad - IT&C category 2023\nHonourable mention at County Computer Science Olympiad 2023\n• 3rd place at the national stage of Innovation and Digital Creativity Olympiad \"InfoEducatie\" - Educational Software category 2021", 5);
    addNode(125, "ActForGreenfootItaly.txt", "txt", "4.0 K", "2026-03-21", "Act for Green Footprint, Not the Global Warming – Pontassieve, Italy | 1 week | 2022\n        • Collaborated with students from Romania, Italy, Turkey, and Greece\n        • Participated in environmental awareness workshops and sustainability activities\n        • Developed teamwork and intercultural communication skills\n\nOrganization: Istituto Comprensivo di PONTASSIEVE", 12);
    addNode(126, "SportsTrainingGreece.txt", "txt", "4.0 K", "2026-03-21", "Sports Vocational Training – Thessaloniki, Greece | 3 weeks | 2023\n        • Trained with an Olympic athletics coach in a sport outside my usual expertise\n        • Learned new techniques, discipline, and adaptability in a high-performance environment\n        • Gained insight into international sports training and coaching methods\n\nOrganization: Education Organization IPODOMI", 12);
    addNode(127, "ClimateActionCyprus.txt", "txt", "4.0 K", "2026-03-21", "From Do Nothing to Do Something for Climate – Cyprus | 1 week\n        • Engaged with peers from Cyprus, Romania, Czech Republic, Greece, and Lithuania\n        • Organized and participated in climate action initiatives\n        • Strengthened leadership, collaboration, and problem-solving skills\n\nOrganization: Harmania Youth Network", 12);
    addNode(128, "basketball.txt", "txt", "4.0 K", "2026-03-21", "Semi-Pro Basketball Player – Division B, Romania | 2 seasons\n            • Competed at semi-professional level\n            • Developed teamwork, discipline, time management", 10);
    addNode(129, "table_official&statistician.txt", "txt", "4.0 K", "2026-03-21", "FIBA Table Official & Statistician – FIBA, International | 2024 - present\n            • Officiated domestic and international games\n            • Managed game timing, scorekeeping, and statistics\n            • Ensured compliance with official basketball rules", 10);
    addNode(130, "CTF_organizer.txt", "txt", "4.0 K", "2026-03-21", "- Organized first city-wide CTF event in Râmnicu Vâlcea (volunteer)\n- Collaborated with team under Project IVI and hashtag#UNbreakableRomania\n- Configured network, designed challenges, and ensured smooth execution\n- Explored reverse engineering, cryptography, pwn, and foundational CTF theory\n- Strengthened teamwork, organizational, and results-oriented skills\n\nLinkedIn post: https://www.linkedin.com/feed/update/urn:li:activity:7440851918542802944/", 11);
    addNode(131, "ProjectIVI_course.txt", "txt", "4.0 K", "2026-03-21", "IT Infrastructure course at Project IVI, Râmnicu Vâlcea\n- Covered CCNA 1 & 2 (network fundamentals, routing, switching)\n- Introduction to Linux: explored system internals and discovered passion for low-level computing\n- Developed basic automation scripts using Bash and Python\n- Gained hands-on experience in configuring networks, managing Linux systems, and automating tasks\n\nProjectIVI website: https://projectivi.ro/", 4);
    addNode(132, "EuropeDirect_volunteer.txt", "txt", "4.0 K", "2026-03-21", "- Participated in local EuropeDirect volunteer association\n- Promoted events and initiatives for city residents\n- Engaged with citizens to raise awareness about EU programs\n\nLink to Facebook page: https://www.facebook.com/europedirectvl/?locale=ro_RO\nLink to EuropeDirect website: https://www.cicvalcea.ro/", 11);
}

int VFS::addNode(int id, std::string name, std::string type, std::string size, std::string date, std::string content, int parent_id) {
    FileNode node;
    node.id = id;
    node.name = name;
    node.type = type;
    node.size = size;
    node.date = date;
    node.content = content;
    node.parent_id = parent_id;

    nodes.push_back(node);

    if (parent_id != -1) {
        for (auto& p : nodes) {
            if (p.id == parent_id && p.type == "dir") {
                p.children_ids.push_back(node.id);
                break;
            }
        }
    }
    return node.id;
}

const FileNode* VFS::getNode(int id) const {
    for (const auto& node : nodes) {
        if (node.id == id) return &node;
    }
    return nullptr;
}

std::vector<int> VFS::getDirectoryContents(int dir_id) const {
    const FileNode* dir = getNode(dir_id);
    if (dir && dir->type == "dir") {
        return dir->children_ids;
    }
    return {};
}
